FROM python:3.9

WORKDIR /app

RUN pip install --no-cache-dir "setuptools<67.0.0" "packaging<24" wheel

RUN pip install --no-cache-dir numpy==1.23.5
RUN pip install --no-cache-dir scikit-surprise==1.1.3 --no-build-isolation

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./scripts /app

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]