FROM apache/airflow:2.7.1-python3.10

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir "setuptools<67.0.0" "packaging<24" wheel
RUN pip install --no-cache-dir numpy==1.23.5 cython
RUN pip install --no-cache-dir scikit-surprise==1.1.3 --no-build-isolation