x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - _AIRFLOW_WWW_USER_USERNAME=admin
    - _AIRFLOW_WWW_USER_PASSWORD=admin
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
  depends_on:
    - postgres

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5430:5432"

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        # Creamos el esquema 'data' para tus alumnos
        psql $AIRFLOW__DATABASE__SQL_ALCHEMY_CONN -c "CREATE SCHEMA IF NOT EXISTS data;"
        # Creamos el usuario
        airflow users create \
            --username admin \
            --firstname Admin \
            --lastname User \
            --role Admin \
            --email admin@example.com \
            --password admin

  scheduler:
    container_name: airflow_scheduler
    <<: *airflow-common
    command: airflow scheduler
    restart: always

  webserver:
    container_name: airflow_webserver
    <<: *airflow-common
    command: airflow webserver
    restart: always
    ports:
      - "8080:8080"

  api:
      build:
        context: .
        dockerfile: Dockerfile.api
      container_name: recommendations_api
      volumes:
        - ./scripts:/app
      working_dir: /app
      ports:
        - "8000:8000"
      command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      depends_on:
        - postgres