FROM apache/airflow:2.7.1-python3.10

USER airflow
# Instalamos los requerimientos y forzamos la instalación del proveedor de postgres
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt \
    && pip install --no-cache-dir apache-airflow-providers-postgres